plugins {
    id 'application'
    id 'idea'
}

description = 'jMe3GL2 - samples'

repositories {
    mavenCentral()
    mavenLocal()
    maven { url = uri("https://jitpack.io") }
}

application {
    if (System.getProperty("os.name").toLowerCase().contains("mac")) {
        applicationDefaultJvmArgs = ['-XstartOnFirstThread'] // this is when using a Mac as a development machine which requires the AppKit main UI thread to be used for GUI applications
    }
}

dependencies {
    // You can read more about how to add dependencies here:
    //   https://docs.gradle.org/current/userguide/dependency_management.html#sec:how_to_declare_your_dependencies

    implementation(libs.bundles.je3gl.base)
    implementation(libs.box2djni)

    runtimeOnly(variantOf(libs.box2djni){ classifier('linux_aarch64Dp') })
    runtimeOnly(variantOf(libs.box2djni){ classifier('linux_aarch64Sp') })
    runtimeOnly(variantOf(libs.box2djni){ classifier('linux_x64Dp') })
    runtimeOnly(variantOf(libs.box2djni){ classifier('linux_x64Sp') })

    runtimeOnly(variantOf(libs.box2djni){ classifier('windows_aarch64Dp') })
    runtimeOnly(variantOf(libs.box2djni){ classifier('windows_aarch64Sp') })
    runtimeOnly(variantOf(libs.box2djni){ classifier('windows_x64Dp') })
    runtimeOnly(variantOf(libs.box2djni){ classifier('windows_x64Sp') })

    runtimeOnly(variantOf(libs.box2djni){ classifier('osx_aarch64Dp') })
    runtimeOnly(variantOf(libs.box2djni){ classifier('osx_aarch64Sp') })
    runtimeOnly(variantOf(libs.box2djni){ classifier('osx_x64Dp') })
    runtimeOnly(variantOf(libs.box2djni){ classifier('osx_x64Sp') })

    runtimeOnly(libs.bundles.je3gl.runtime)

    implementation project(':modules:libraries:jMe3GL2-core')
    implementation project(':modules:libraries:jMe3GL2-jawt')
    implementation project(':modules:libraries:jMe3GL2-dyn4j')
    implementation project(':modules:libraries:jMe3GL2-box2d')
    implementation project(':modules:libraries:jMe3GL2-plugins')
}
